on: [push, pull_request]
name: Lint code and commits
jobs:
  lint-code:
    runs-on: ubuntu-latest
    container:
      image: timbru31/ruby-node:3.0-16
    steps:
      - uses: actions/checkout@v2.3.1
      - run: chmod -R 777 .
      - run: npm ci
      - run: npm run lint-js
      - run: npm run lint-scss
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.0
      - run: npm install @commitlint/cli
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
